#101-lazy_matrix_mul.txt 

This module accepts two parameter(matrix)
and multiply them

importing the module for the first time
---------------------------------------

>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul
    >>> m_a = [
    ... [1, 1],
    ... [3, 4]
    ... ]
    >>> m_b = m_a
    >>> print(lazy_matrix_mul(m_a, m_b))
    [[ 4  5]
     [15 19]]
    
    >>> m_a =  [[1, 2]]
    >>> m_b = [[3, 4], [4, 5]]
    >>> print(lazy_matrix_mul(m_a, m_b))
    [[11 14]]

    >>> m_a = [
    ... [1.5, 9.6, 2.4],
    ... [3.1, 4.2, -2.1]
    ... ]
    >>> m_b = [
    ... [2.1, 3.1],
    ... [9.3, -4.1],
    ... [2.1, 2.5]
    ... ]
    >>> print(lazy_matrix_mul(m_a, m_b))
    [[ 97.47 -28.71]
     [ 41.16 -12.86]]

    >>> print(lazy_matrix_mul(m_a))
    Traceback (most recent call last):
    TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'

    >>> print(lazy_matrix_mul())
    Traceback (most recent call last):
    TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'
    
Testing for value Errors
------------------------

    >>> m_a = [
    ... [2, 3],
    ... [4, 6]
    ... ]
    >>> m_b = [
    ... [2, 4],
    ... [5, 6],
    ... [6, 7]
    ... ]
    >>> print(lazy_matrix_mul(m_a, m_b))
    Traceback (most recent call last):
    ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

Testing for empty parameters
----------------------------

    >>> print(lazy_matrix_mul([[]], [[3, 6], [9, 8]]))
    Traceback (most recent call last):
    ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 0)

Testing for invalid matrix
    >>> print(lazy_matrix_mul("This is string", [[1, 2]]))
    Traceback (most recent call last):
    ValueError: Scalar operands are not allowed, use '*' instead

   >>> print(lazy_matrix_mul([[1, 3]], "This is a string"))
   Traceback (most recent call last):
   ValueError: Scalar operands are not allowed, use '*' instead
   
   >>> print(lazy_matrix_mul("This is a string", "This a string"))
   Traceback (most recent call last):
   ValueError: Scalar operands are not allowed, use '*' instead

   >>> print(lazy_matrix_mul(None, None))
   Traceback (most recent call last):
   TypeError: Object arrays are not currently supported

   >>> print(lazy_matrix_mul([1, 2], [[3, 4]]))
   Traceback (most recent call last):
   ValueError: shapes (2,) and (1,2) not aligned: 2 (dim 0) != 1 (dim 0)
  
   >>> print(lazy_matrix_mul([[2, 5]], [3, 4]))
   [26]

   >>> print(lazy_matrix_mul([[1, "not a number"]], [[3, 4]]))
   Traceback (most recent call last):
   ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

   >>> print(lazy_matrix_mul([[2, 6], [2, 1]], [[11, "6"], [5, 10]])
   Traceback (most recent call last):
   TypeError: invalid data type for einsum

   >>> print(lazy_matrix_mul([[4, "not a number"]], [[{"b": 2}, 5.8]]))
   Traceback (most recent call last):
   TypeError: Object arrays are not currently supported

 
